x=float(input("enter your marks here"))
if x < 0:
    print("please enter a valid marks")
elif x>90:
    print("you passed with a A+ grade")
elif x >85:
    print("you passed with a A grade")
elif x > 70:
    print("you passed with a B grade")
elif x > 60:
    print("you passed with a C grade")
elif x > 50:
    print("you passed with a D grade")
elif x > 40:
    print("you passed with a E grade")
elif x > 20:
    print(" you passed with a F grade  F is lowwer grade you need to strrugle ")
else:
    print(" sorry! you are failed")




